workaround annoying MSVC bugs
https://developercommunity.visualstudio.com/t/compilation-fails-with-brace-initializer-for-const/447124

./api/context.cpp(24): error C2440: 'initializing': cannot convert from 'const char [14]' to 'const char [1]'
../api/context.cpp(24): note: The string literal is too long
../api/context.cpp(24): error C2440: 'initializing': cannot convert from 'const char [4]' to 'const char [1]'
../api/context.cpp(24): note: The string literal is too long
C:\projects\reaimgui\api\compstr.hpp(54): error C2131: expression did not evaluate to a constant
C:\projects\reaimgui\api\compstr.hpp(54): note: failure was caused by a read of an uninitialized symbol
C:\projects\reaimgui\api\compstr.hpp(54): note: see usage of 'vn'
C:\projects\reaimgui\api\compstr.hpp(54): note: the template instantiation context (the oldest one first) is
../api/context.cpp(24): note: see reference to variable template 'const char *const version<&API::v0_5::CreateContext::meta::vn>' being compiled
C:\projects\reaimgui\api\compstr.hpp(70): note: see reference to class template instantiation 'CompStr::Version<& vn>' being compiled
C:\projects\reaimgui\api\compstr.hpp(52): note: while compiling class template member function 'auto CompStr::Version<& vn>::compute(void)'
C:\projects\reaimgui\api\compstr.hpp(55): error C2131: expression did not evaluate to a constant
C:\projects\reaimgui\api\compstr.hpp(54): note: failure was caused by a read of an uninitialized symbol
C:\projects\reaimgui\api\compstr.hpp(54): note: see usage of 'vn'
C:\projects\reaimgui\api\compstr.hpp(56): error C2131: expression did not evaluate to a constant
C:\projects\reaimgui\api\compstr.hpp(54): note: failure was caused by a read of an uninitialized symbol
C:\projects\reaimgui\api\compstr.hpp(54): note: see usage of 'vn'
C:\projects\reaimgui\api\compstr.hpp(57): error C2975: '_Size': invalid template argument for 'std::array', expected compile-time constant expression
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\array(405): note: see declaration of '_Size'
C:\projects\reaimgui\api\compstr.hpp(66): error C2131: expression did not evaluate to a constant
C:\projects\reaimgui\api\compstr.hpp(54): note: failure was caused by a read of an uninitialized symbol
C:\projects\reaimgui\api\compstr.hpp(54): note: see usage of 'vn'
../api/context.cpp(24): error C2131: expression did not evaluate to a constant
C:\projects\reaimgui\src\vernum.hpp(42): note: failure was caused by unevaluable pointer value