ci: build for arm64 with Xcode 14 on macOS 12
Previous commit dropped the dependency on php which stopped being shipped in macOS.

Xcode 14 dropped support for targetting macOS 10.9-10.12 so it can't be used for the x86_64 build.

Xcode 13 is broken too:

    /Applications/Xcode-13.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__functional/function.h:233:7: error: use of undeclared identifier '__builtin_new_allocator'
          __builtin_new_allocator::__holder_t __hold =
          ^